# Generated by Django 4.0.3 on 2022-03-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
